ARG sourceimage=freqtradeorg/freqtrade
ARG sourcetag=stable

FROM ${sourceimage}:${sourcetag}

USER root
RUN pip install --upgrade pip && \
    pip install --no-build-isolation --no-cache-dir numba

USER ftuser
ENV PATH=/home/ftuser/.local/bin:$PATH
