ARG sourceimage=freqtradeorg/freqtrade
ARG sourcetag=stable
FROM ${sourceimage}:${sourcetag}
USER root

# RUN apt-get update; \
# 	apt-get install -y --no-install-recommends git git-lfs; \
# 	\
# 	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
# 	rm -rf /var/lib/apt/lists/*

COPY --chown=1000:1000  tests/requirements.txt /freqtrade
USER ftuser
RUN pip install --upgrade pip && pip install --user --no-cache-dir --no-build-isolation -r /freqtrade/requirements.txt
